### ISSUE TITLE
Split neighbor on ; and \n

### ISSUE THREAD

**Issue by eloekset** [Jotne/MikroTik#5]
I'm not sure whether this is a real issue, but it looks like the split on "\n" works for most, but not all properties. From my syslog:
![image](https://github.com/Jotne/MikroTik/assets/791721/77217a3b-1079-49bb-8d39-a01e4b18f97c)

I cannot reproduce the output running the `/ip neighbor get` command on the terminal, but I'm just guessing that some of these properties are split by semicolon.

I haven't tested it, but maybe this would split by both newline and semicolon?
```
:local semicolon [:find $value ";"]
:if ([$newline]>0 or [$semicolon]>0) do = {
```
![image](https://github.com/Jotne/MikroTik/assets/791721/165d793f-f4cf-4a36-9d6c-cde84f3f0665)

I may also break things if Mikrotik should choose to use semicolons in their content somewhere.

**Comment by Jotne** [comment]
This is some strange, since for me it looks correct in rsyslog logs.  All fields are on each line, but will have a detailed look to it.
![script](https://github.com/Jotne/MikroTik/assets/17832289/eeccbc06-6f74-43c4-8a22-d9221ce8266d)

**Comment by Jotne** [comment]
Try this in a terminal window to see the output on the router.

`{
:foreach neighborID in=[/ip neighbor find] do={
:local nb [/ip neighbor get $neighborID]
:local id [:pick ("$nb"->".id") 1 99]
:foreach key,value in=$nb do={
:local newline [:find $value "\n"]
:if ([$newline]>0) do={
:set value [:pick $value 0 $newline]
}
:put "script=neighbor nid=$id $key=\"$value\""
}
}
}
`

**Comment by Jotne** [comment]
I thought I did not see the problem. But on a router with 7.11b2 I do see the error, will tryfix

**Comment by Jotne** [comment]
This is a but in RouterOS.  It fails to spilt Key Value correctly on some version.

**Comment by Jotne** [comment]
Mostly fixed in latest commit.  Problem was multi value fields.  Like a neighbor router my be discovered by several type of protocol

**Comment by eloekset** [comment]
Thanks! I've updated the view file on the Splunk app and the script on all of my devices. I'll report back once the neighbor part has been logged again.

**Comment by Jotne** [comment]
Fixed with better extraction code.
