### ISSUE TITLE
Add-ons and Apps

### ISSUE THREAD

**Issue by amirulalif** [Jotne/MikroTik#6]
Hello,

Just want to ask two questions, 
First, i was wondering did you have plan to separate this MikroTik into Add-ons and Apps?
Second, this apps does not yet available on [Splunkbase](https://splunkbase.splunk.com/) right? because i can't find it there.

Thanks

**Comment by Jotne** [comment]
First:  Have not thought about that.  Like a TA app and a Dashboard app?
Second:  Its not there of several reason.  It started as a hobby project and have not had time to do it, and not felt the quality are good enough :)
But I was thinking about putting on Splunk base.

**Comment by amirulalif** [comment]
First: Yes two different apps. It will help to shipped with Universal Forwarder when using syslog server
Second: The quality of this apps its good for me. Thanks to you, it help me a lot. If this app on splunkbase it's easy for splunk user to get the latest updated version

**Comment by Jotne** [comment]
Thanks for your comment.  I will look inn to it.  My experience is that most of the app I do download I have to split my self, and they are not prepared for setup with UF -> HF -> Indexers.
